# Generated by Django 5.0.6 on 2025-09-17 10:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(default='system', max_length=100)),
                ('type', models.CharField(choices=[('WEBHOOK_RECEIVED', 'Webhook Received'), ('WEBHOOK_CREATED', 'Webhook Created'), ('WEBHOOK_UPDATED', 'Webhook Updated'), ('WEBHOOK_DELETED', 'Webhook Deleted'), ('SECRET_ROTATED', 'Secret Rotated'), ('REPLAY_TRIGGERED', 'Replay Triggered'), ('REPLAY_SUCCESS', 'Replay Success'), ('REPLAY_FAILED', 'Replay Failed'), ('FORWARD_TRIGGERED', 'Forward Triggered'), ('FORWARD_SUCCESS', 'Forward Success'), ('FORWARD_FAILED', 'Forward Failed'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('API_KEY_CREATED', 'API Key Created'), ('API_KEY_DELETED', 'API Key Deleted'), ('USER_REGISTERED', 'User Registered'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('SYSTEM_ERROR', 'System Error')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, choices=[('webhook', 'Webhook'), ('event', 'Event'), ('user', 'User'), ('replay', 'Replay'), ('forward', 'Forward'), ('system', 'System')], max_length=50, null=True)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx'), models.Index(fields=['type', '-created_at'], name='activity_lo_type_c1fe95_idx'), models.Index(fields=['target_type', 'target_id'], name='activity_lo_target__1703db_idx'), models.Index(fields=['is_system', '-created_at'], name='activity_lo_is_syst_fe5389_idx')],
            },
        ),
    ]
