# Generated by Django 5.0.6 on 2025-09-17 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='body_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='body_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='is_duplicate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='raw_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='raw_headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('forwarded', 'Forwarded')], db_index=True, default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['endpoint', '-created_at'], name='webhook_eve_endpoin_037038_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', '-created_at'], name='webhook_eve_status_1be6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['body_hash'], name='webhook_eve_body_ha_ee94a9_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['request_id'], name='webhook_eve_request_605900_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['source_ip', '-created_at'], name='webhook_eve_source__c062d2_idx'),
        ),
    ]
