# Generated by Django 5.0.6 on 2025-09-17 09:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhookevent_body_hash_webhookevent_body_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookForward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='webhooks.webhookevent')),
            ],
            options={
                'verbose_name': 'Webhook Forward',
                'verbose_name_plural': 'Webhook Forwards',
                'db_table': 'webhook_forwards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookReplay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='webhooks.webhookevent')),
            ],
            options={
                'verbose_name': 'Webhook Replay',
                'verbose_name_plural': 'Webhook Replays',
                'db_table': 'webhook_replays',
                'ordering': ['-created_at'],
            },
        ),
    ]
